# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            F5
tagline:          'A simple blog'
description:      'A simple blog'
url:              https://ankitbko.github.io
baseurl:          /

author:
  name:           'Ankit Sinha'
  url:            https://github.com/ankitbko

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ankitbko

gems: [jekyll-paginate, jekyll-gist]